# ==========================================
# CẤU HÌNH DATABASE AIVEN MYSQL (Bắt buộc SSL)
# ==========================================

# Thêm sslMode=REQUIRED và bỏ createDatabaseIfNotExist
spring.datasource.url=jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?sslMode=REQUIRED

spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true